name: Build Solution

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    outputs:
      coverage: ${{ steps.test.outputs.COVERAGE }}
    
    strategy:
      matrix:
          os: [ubuntu-latest]
          node-version: [12.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'  # Replace with the correct version

    - name: Restore dependencies
      run: dotnet restore --no-cache

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      id: test
      run: |
        TEST_OUTPUT=$(dotnet test --no-build /p:CollectCoverage=true /p:ExcludeByFile="**/*Migrations/*.cs" --logger trx)
        echo "$TEST_OUTPUT"

        TOTAL_COVERAGE=$(echo "$TEST_OUTPUT" | grep "| Total" | awk '{print $4}' | tr -d '%')
        echo "Total Coverage: $TOTAL_COVERAGE"
        
        echo "COVERAGE=$TOTAL_COVERAGE" >> "$GITHUB_OUTPUT"

  update-badge:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract Coverage
      run: |
        COVERAGE=${{needs.build.outputs.coverage}}
        echo "Coverage: $COVERAGE"

    - name: Update Badge
      run: |

        # COVERAGE=${{needs.build.outputs.coverage}}
        # echo "Coverage: $COVERAGE"

        BADGE_COLOR=""
            
        if (( $(awk -v cov="$COVERAGE" 'BEGIN{ print (cov < 30) }') )); then
          BADGE_COLOR="red"
        elif (( $(awk -v cov="$COVERAGE" 'BEGIN{ print (cov >= 30 && cov < 75) }') )); then
          BADGE_COLOR="yellow"
        else
          BADGE_COLOR="brightgreen"
        fi
 
        echo "BADGE_COLOR: $BADGE_COLOR"

        BADGE_URL="https://img.shields.io/badge/Coverage-${COVERAGE}%25-${BADGE_COLOR}.svg"
        echo "[![Coverage Status](${BADGE_URL})](https://your_coverage_report_url_here)" > README.md
        
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        git add README.md
        git commit -m "Update coverage badge [skip ci]"
      
        BRANCH_NAME=$(basename ${{ github.ref }} | sed 's/refs\/heads\///')
        git branch -M $BRANCH_NAME
        git push origin $BRANCH_NAME
