name: Build Solution

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
          node-version: [12.x]


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'  # Replace with the correct version

    - name: Restore dependencies
      run: dotnet restore LibMS.API.sln --no-cache

    - name: Build
      run: dotnet build LibMS.API.sln --no-restore

    - name: Test
      run: dotnet build LibMS.API.sln --no-build /p:CollectCoverage=true /p:ExcludeByFile="**/*Migrations/*.cs"
