name: Build Solution

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    
    strategy:
      matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
          node-version: [12.x]


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'  # Replace with the correct version

    - name: Restore dependencies
      run: dotnet restore --no-cache

    - name: Build
      run: dotnet build --no-restore

    - name: Update Badge
      run: |
        # Extract coverage percentage from your coverage report (replace with your actual command)
        COVERAGE=$(dotnet test --no-build /p:CollectCoverage=true /p:ExcludeByFile="**/*Migrations/*.cs" --logger trx | grep "Total Coverage" | awk '{print $3}')
    
        # Generate and update the badge URL
        BADGE_URL="https://img.shields.io/badge/Coverage-${COVERAGE}%25-brightgreen.svg"
        echo "[![Coverage Status](${BADGE_URL})](https://your_coverage_report_url_here)" > README.md
        
        git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
        git config --global user.name ${{ secrets.GIT_USER_NAME }}
        git add README.md
        git commit -m "Update coverage badge [skip ci]"  # <-- Include [skip ci] here
        git branch -M ${{ github.ref }}
        git push origin ${{ github.ref }}

